services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-12345678}
            POSTGRES_DB: ${DB_DATABASE:-app}
        volumes:
            - postgres-data:/var/lib/postgresql/data
    # redis:
    #     image: redis:latest
    #     restart: always
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - redis_data:/data
    #     environment:
    #         - REDIS_PORT=6379
    #         - REDIS_PASSWORD=${REDIS_PASSWORD:-12345678}
    #         - REDIS_DATABASE=1

volumes:
    postgres-data:
    # redis_data: